version: 0.2

phases:
  install: # 사전에 설치 할 항목
    runtime-versions:
      nodejs: 12 # 노드 버전은 정해져있는 거 같음. 8, 10
  pre_build: # Build 전에 할 작업
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build: # Build
    commands:
      - echo Build started on `date`
      - npm run build
  post_build: # Build 완료 후에 할 작업
    commands:
      - rm -rf node_modules
      - rm -rf buildspec.yml
      - rm -rf package.json
      - rm -rf package-lock.json
      - rm -rf public
      - rm -rf README.md
      - rm -rf src
      - rm -rf yarn.lock
artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "build"
