version: 0.2

phases:
  install: # 사전에 설치 할 항목
    runtime-versions:
      nodejs: 10 # 노드 버전은 정해져있는 거 같음. 8, 10
  pre_build: # Build 전에 할 작업
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build: # Build
    commands:
      - echo Build started on `date`
      - npm run build
  post_build: # Build 완료 후에 할 작업
    commands:
      # copy the contents of /build to S3
      # - aws s3 cp --recursive --acl public-read ./build s3://code-pipeline-test-s3/
      - tar cvzf deploy.tar build
      - aws s3 cp deploy.tar s3://code-pipeline-test-s3/
      - aws s3 cp ./appspec.yml s3://code-pipeline-test-s3/
      - aws s3 cp ./deploy.sh s3://code-pipeline-test-s3/

      # set the cache-control headers for service-worker.js to prevent
      # browser caching
      # - >
      #   aws s3 cp --acl public-read
      #   --cache-control="max-age=0, no-cache, no-store, must-revalidate"
      #   ./build/service-worker.js s3://aws-codebuild-test-s3/

      # set the cache-control headers for index.html to prevent
      # browser caching
      # - >
      #   aws s3 cp --acl public-read
      #   --cache-control="max-age=0, no-cache, no-store, must-revalidate"
      #   ./build/index.html s3://code-pipeline-test-s3/
artifacts:
  files:
    - "deploy.tar"
  # base-directory: build
