version: "3.7"
services:
  app:
    container_name: aws-codepipeline-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
